variable "project_name" {
  type        = string
  description = "Name of the project."
}

variable "namespace" {
  type        = string
  description = "Namespace for the resources."
  default     = "arc-demo"
}

variable "region" {
  type        = string
  description = "AWS Region"
  default     = "ap-south-1"
}

variable "environment" {
  type        = string
  default     = "dev"
  description = "ID element. Usually used for region e.g. 'uw2', 'us-west-2', OR role 'prod', 'staging', 'dev', 'UAT'"
}

variable "availability_zones" {
  description = "List of availability zones to deploy resources in."
  type        = list(string)

  default = [
    "ap-south-1a",
    "ap-south-1b"
  ]
}

variable "vpc_cidr_block" {
  description = "CIDR block for the VPC to use."
  default     = "10.0.0.0/16"
  type        = string
}

# variable "vpc_ipv4_primary_cidr_block" {
#   description = "Primary ipv4 CIDR block for VPC"
#   default     = "10.0.0.0/16"
# }

# variable "generate_ssh_key" {
#   type        = bool
#   description = "Whether or not to generate an SSH key"
#   default     = true
# }

# variable "ssh_key_path" {
#   type        = string
#   description = "Save location for ssh public keys generated by the module"
#   default     = "./secrets"
# }
